browser/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

app_name = 'browser'
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="browser/home.html")),
    url(r'^home$', TemplateView.as_view(template_name="browser/home.html"), name='home'),
    url(r'^download$', TemplateView.as_view(template_name="browser/download.html"), name='download'),
    url(r'^nutrition$', TemplateView.as_view(template_name="browser/nutrition_us.html"), name='nutrition'),
    url(r'^search$', views.search_gtin, name='search'),
    url(r'^brand-list-(?P<page_id>[a-z0-9]+)$', views.ViewBrandList.as_view(), name='brand_list'),
    url(r'^brand-(?P<bsin>[a-zA-Z0-9]+)$', views.ViewBsin.as_view(), name='bsin'),
    url(r'^gtin-(?P<pk>[0-9]+)$', views.ViewGtin.as_view(), name='gtin'),
    url(r'^owner-list$', views.ViewOwnerList.as_view(), name='owner_list'),
    url(r'^owner-(?P<owner>[a-zA-Z0-9]+)$', views.ViewOwner.as_view(), name='owner'),
    # provide images stored in the database
    url(r'^gtin-img-(?P<pk>[0-9]+)$', views.Show_gtin_img, name='show_gtin_img'),
    url(r'^brand-img-(?P<pk>[a-zA-Z0-9]+)$', views.Show_brand_img, name='show_brand_img'),
    url(r'^owner-img-(?P<pk>[a-zA-Z0-9]+)$', views.Show_owner_img, name='show_owner_img'),
]

opd/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from browser import views


urlpatterns = [
	url(r'^', include('browser.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/gtin/(?P<pk>[0-9]+)/$', views.RestViewGtinDetail.as_view()),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

browser/models.py
from django.db import models


class Gtin_img(models.Model):
    GTIN_CD = models.CharField(max_length=13, primary_key=True)
    GTIN_IMG = models.BinaryField()

class Brand_img(models.Model):
    BSIN = models.CharField(max_length=6, primary_key=True)
    BSIN_IMG = models.BinaryField()

class Brand_owner_img(models.Model):
    OWNER_CD = models.IntegerField(primary_key=True)
    OWNER_IMG = models.BinaryField()

# Gtin contains products with a GTIN-13
class Gtin(models.Model):
    GTIN_CD = models.CharField(max_length=13, primary_key=True)
    GTIN_LEVEL_CD = models.IntegerField(default=0, null=True, blank=True)
    GCP_CD = models.ForeignKey('Gs1_gcp', null=True, blank=True)
    BSIN = models.ForeignKey('Brand', null=True, blank=True)
    GPC_S_CD = models.ForeignKey('Gs1_gpc', null=True, blank=True, related_name='GPC_S_CD')
    GPC_F_CD = models.ForeignKey('Gs1_gpc', null=True, blank=True, related_name='GPC_F_CD')
    GPC_C_CD = models.ForeignKey('Gs1_gpc', null=True, blank=True, related_name='GPC_C_CD')
    GPC_B_CD = models.ForeignKey('Gs1_gpc', null=True, blank=True, related_name='GPC_B_CD')
    GTIN_NM = models.CharField(max_length=255, null=True, blank=True)
    PRODUCT_LINE = models.CharField(max_length=255, null=True, blank=True)
    M_G = models.FloatField(null=True, blank=True)
    M_OZ = models.FloatField(null=True, blank=True)
    M_ML = models.FloatField(null=True, blank=True)
    M_FLOZ = models.FloatField(null=True, blank=True)
    M_ABV = models.FloatField(null=True, blank=True)
    M_ABW = models.FloatField(null=True, blank=True)
    PKG_UNIT = models.IntegerField(default=0, null=True, blank=True)
    PKG_TYPE_CD = models.IntegerField(null=True, blank=True)
    REF_CD = models.CharField(max_length=255, null=True, blank=True)
    SOURCE = models.CharField(max_length=255, null=True, blank=True)
    IMG = models.IntegerField(default=0, null=True, blank=True)
    def __str__(self):
        return self.GTIN_CD

class Brand(models.Model):
    BSIN = models.CharField(max_length=6, primary_key=True)
    BRAND_NM = models.CharField(max_length=255)
    BRAND_TYPE_CD = models.ForeignKey('Brand_type', null=True, blank=True)
    BRAND_LINK = models.CharField(max_length=255, null=True, blank=True)
    OWNER_CD = models.ForeignKey('Brand_owner', null=True, blank=True)
    def __str__(self):
        return self.BSIN

class Brand_type(models.Model):
    BRAND_TYPE_CD = models.IntegerField(primary_key=True)
    BRAND_TYPE_NM = models.CharField(max_length=255, null=True, blank=True)
    def __str__(self):
        return self.BRAND_TYPE_NM

class Nutrition(models.Model):
    GTIN_CD  = models.OneToOneField(
        Gtin,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    INGREDIENTS = models.TextField(null=True, blank=True)
    SERV_SIZE_G = models.FloatField(null=True, blank=True)
    SERV_SIZE_ML = models.FloatField(null=True, blank=True)
    SERV_CT = models.FloatField(null=True, blank=True)
    CAL = models.FloatField(null=True, blank=True)
    CAL_FROM_FAT = models.FloatField(null=True, blank=True)
    TOT_FAT_G = models.FloatField(null=True, blank=True)
    TOT_FAT_DV = models.FloatField(null=True, blank=True)
    SAT_FAT_G = models.FloatField(null=True, blank=True)
    SAT_FAT_DV = models.FloatField(null=True, blank=True)
    TRANS_FAT_G = models.FloatField(null=True, blank=True)
    CHOL_MG = models.FloatField(null=True, blank=True)
    CHOL_DV = models.FloatField(null=True, blank=True)
    SOD_MG = models.FloatField(null=True, blank=True)
    SOD_DV = models.FloatField(null=True, blank=True)
    POT_MG = models.FloatField(null=True, blank=True)
    POT_DV = models.FloatField(null=True, blank=True)
    TOT_CARB_G = models.FloatField(null=True, blank=True)
    TOT_CARB_DV = models.FloatField(null=True, blank=True)
    DIET_FIBER_G = models.FloatField(null=True, blank=True)
    DIET_FIBER_DV = models.FloatField(null=True, blank=True)
    SUGARS_G = models.FloatField(null=True, blank=True)
    PROTEIN_G = models.FloatField(null=True, blank=True)
    VITAMIN_A = models.FloatField(null=True, blank=True)
    VITAMIN_C = models.FloatField(null=True, blank=True)
    CALCIUM = models.FloatField(null=True, blank=True)
    IRON = models.FloatField(null=True, blank=True)
    SOURCE = models.TextField(null=True, blank=True)
    SYNC_DT = models.DateField(null=True, blank=True)

class Gs1_gpc(models.Model):
    GPC_LANG = models.CharField(max_length=3)
    GPC_CD = models.CharField(max_length=20, primary_key=True)
    GPC_NM = models.TextField()
    GPC_LEVEL = models.CharField(max_length=1)
    SOURCE = models.CharField(max_length=255)

class Gs1_gpc_hier(models.Model):
    GPC_S_CD = models.CharField(max_length=8)
    GPC_F_CD = models.CharField(max_length=8)
    GPC_C_CD = models.CharField(max_length=8)
    GPC_B_CD = models.CharField(max_length=8, primary_key=True)

class Brand_owner(models.Model):
    OWNER_CD = models.IntegerField(primary_key=True)
    OWNER_NM = models.CharField(max_length=255, null=True, blank=True)
    OWNER_LINK = models.CharField(max_length=255, null=True, blank=True)
    OWNER_WIKI_EN = models.CharField(max_length=255, null=True, blank=True)

class Gs1_gcp(models.Model):
    GCP_CD = models.CharField(max_length=13, primary_key=True)
    GLN_CD = models.CharField(max_length=13)
    GLN_NM = models.CharField(max_length=255)
    GLN_ADDR_02 = models.CharField(max_length=38)
    GLN_ADDR_03 = models.CharField(max_length=38)
    GLN_ADDR_04 = models.CharField(max_length=38)
    GLN_ADDR_POSTALCODE = models.CharField(max_length=38)
    GLN_ADDR_CITY = models.CharField(max_length=38)
    GLN_COUNTRY_ISO_CD = models.CharField(max_length=38)
    CONTACT_NAME = models.CharField(max_length=38)
    CONTACT_TEL = models.CharField(max_length=255)
    CONTACT_HOTLINE = models.CharField(max_length=255, null=True, blank=True)
    CONTACT_FAX = models.CharField(max_length=255)
    CONTACT_MAIL = models.CharField(max_length=255)
    CONTACT_WEB = models.CharField(max_length=255)
    GLN_LAST_CHANGE = models.CharField(max_length=10)
    GLN_PROVIDER = models.CharField(max_length=13)
    SEARCH_GTIN_CD = models.CharField(max_length=13)
    GEPIR_GCP_CD = models.CharField(max_length=13)
    ADD_PARTY_ID = models.CharField(max_length=13)
    RETURN_CODE = models.ForeignKey('Gs1_gcp_rc', null=True, blank=True)
    SOURCE = models.CharField(max_length=100)
    SYNC_DT = models.DateField(null=True, blank=True)
    def __str__(self):
        return self.GCP_CD

class Gs1_gcp_rc(models.Model):
    RETURN_CODE = models.CharField(max_length=3, primary_key=True)
    RETURN_NAME = models.CharField(max_length=255)
    ORIGIN = models.CharField(max_length=255)

# Search is used to store gtin that people are searching and the number of times it has been searched
class Search(models.Model):
    GTIN_CD = models.CharField(max_length=13, primary_key=True)
    SEARCH_NB =  models.IntegerField(default=1)

# same but for the API
class Search_api(models.Model):
    GTIN_CD = models.CharField(max_length=13, primary_key=True)
    SEARCH_NB =  models.IntegerField(default=1)

browser/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Gtin, Nutrition, Brand, Brand_owner, Search, Gtin_img, Brand_img, Brand_owner_img

# import for REST

from browser.serializers import GtinSerializer
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

import requests

# --------------------------------------------------------------------
#  WEBSITE BROWSER
# --------------------------------------------------------------------

def Show_gtin_img(request,pk):
    # 1. If images are stored in database
    #BinaryImg = Gtin_img.objects.get(pk=pk).GTIN_IMG,
    #return HttpResponse(BinaryImg, 'image/jpg')

    # 2. If images are stored on amazon S3
    return HttpResponse(requests.get('http://product.okfn.org.s3.amazonaws.com/images/gtin/gtin-' + pk[0:3] + '/' + pk + '.jpg' ), 'image/jpg')

def Show_brand_img(request,pk):
    # 1. If images are stored in database
    #BinaryImg = Brand_img.objects.get(pk=pk).BSIN_IMG,
    #return HttpResponse(BinaryImg, 'image/jpg')

    # 2. If images are stored on amazon S3
    return HttpResponse(requests.get('http://product.okfn.org.s3.amazonaws.com/images/brand/' + pk + '.jpg' ), 'image/jpg')

def Show_owner_img(request,pk):
    # 1. If images are stored in database
    #BinaryImg = Brand_owner_img.objects.get(pk=pk).OWNER_IMG,
    #return HttpResponse(BinaryImg, 'image/jpg')

    # 2. If images are stored on amazon S3
    return HttpResponse(requests.get('http://product.okfn.org.s3.amazonaws.com/images/owner/' + pk + '.jpg' ), 'image/jpg')

def search_gtin(request):
    if Search.objects.filter(pk=request.POST['gtin']).exists():
        search_gtin = Search.objects.get(pk=request.POST['gtin'])
        search_gtin.SEARCH_NB += 1
        search_gtin.save()
    else:
        new_entry = Search(GTIN_CD = request.POST['gtin'], SEARCH_NB = 1)
        new_entry.save()

    try:
        if request.POST['gtin']:
            gtin = Gtin.objects.get(pk=request.POST['gtin'])
    except (KeyError, Gtin.DoesNotExist):
        return render(request, 'browser/home.html', {
            'error_message': "This GTIN is not in the database",
        })
    else:
        return HttpResponseRedirect(reverse('browser:gtin', args=(gtin,)))

class ViewGtin(generic.DetailView):
    template_name = 'browser/gtin.html'
    model = Gtin

    queryset = Gtin.objects.all()

    def get_object(self):
        object = super(ViewGtin, self).get_object()
        if object.GTIN_CD and object.GTIN_CD[0:1] == "0":
            object.UPC_CD = object.GTIN_CD[1:12]
        object.save()
        return object

class ViewBrandList(generic.ListView):
    template_name = 'browser/brand_list.html'
    context_object_name = 'page_brand_list'
    model = Brand

    def get_context_data(self, **kwargs):
        context = super(ViewBrandList, self).get_context_data(**kwargs)
        context.update({
            'page_id': self.kwargs['page_id'],
        })
        return context

    def get_queryset(self):
        page_id = 'A'
        page_id = self.kwargs['page_id']
        return Brand.objects.filter(BRAND_NM__istartswith=page_id).order_by('BRAND_NM')

class ViewBsin(generic.ListView):
    template_name = 'browser/bsin.html'
    context_object_name = 'gtin_list'
    model = Gtin

    def get_context_data(self, **kwargs):
        context = super(ViewBsin, self).get_context_data(**kwargs)
        context.update({
            'bsin_detail': Brand.objects.get(pk=self.kwargs['bsin']),
        })
        return context

    def get_queryset(self):
        bsin = self.kwargs['bsin']
        return Gtin.objects.filter(BSIN=bsin).order_by('PRODUCT_LINE','PKG_UNIT','GTIN_NM')

class ViewOwnerList(generic.ListView):
    template_name = 'browser/brand_owner_list.html'
    context_object_name = 'owner_list'
    model = Brand_owner

    def get_queryset(self):
        """Return the last five published questions."""
        return Brand_owner.objects.order_by('OWNER_NM')

class ViewOwner(generic.ListView):
    template_name = 'browser/brand_owner.html'
    context_object_name = 'brand_list'
    model = Brand

    def get_context_data(self, **kwargs):
        context = super(ViewOwner, self).get_context_data(**kwargs)
        context.update({
            'owner_detail': Brand_owner.objects.get(pk=self.kwargs['owner']),
        })
        return context

    def get_queryset(self):
        """Return the last five published questions."""
        owner = self.kwargs['owner']
        return Brand.objects.filter(OWNER_CD=owner).order_by('BRAND_NM')

# --------------------------------------------------------------------
#   REST API DRF
# --------------------------------------------------------------------

# gtin for test : 0836093401314    0857063002652

class RestViewGtinDetail(APIView):
    def get_object(self, pk):
        try:
            return Gtin.objects.get(pk=pk)
        except Gtin.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        gtin = self.get_object(pk)
        serializer = GtinSerializer(gtin)
        return Response(serializer.data)

browser/templates/browser/base.html
<!DOCTYPE html>
<html lang="en" prefix="og: http://ogp.me/ns#">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<meta name="description" content="The world's largest open product database joins Open Knowledge Foundation and you can get involved!">
		<meta name="keywords" content="Product, GS1, GTIN, GLN, Big Data, MDM, Open Data">
    <meta name="author" content="">

    <meta property="og:url" content="http://www.product-open-data.com/">
    <meta property="og:site_name" content="Open Product Data" >
    <meta property="og:title" content="Open Product Data" >
    <meta property="og:description" content="The world's largest open product database joins Open Knowledge Foundation and you can get involved!" >
    <meta property="og:type" content="website" >
    <meta property="og:author" content='https://okfn.org/' >
    <meta property="og:image" content="http://www.product-open-data.com/static/browser/img/opd_logo_400.png" >
    <meta property="og:image:width" content="400" >
    <meta property="og:image:height" content="400" >

    <meta property="twitter:card" content="summary_large_image" >
    <meta property="twitter:site" content="@openproductdata" >
    <meta property="twitter:creator" content='@OKFN' >
    <meta property="twitter:title" content="Open Product Data" >
    <meta property="twitter:description" content="The world's largest open product database joins Open Knowledge Foundation and you can get involved!" >
    <meta property="twitter:image:src" content="http://www.product-open-data.com/static/browser/img/opd_logo_400.pngg" >
    <meta property="twitter:image:width" content="400" >
    <meta property="twitter:image:height" content="400" >

		<link rel="icon" href="{% static 'browser/img/favicon.ico' %}">

    <title>OPD - Open Product Data</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'browser/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'browser/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'browser/css/opd.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'browser/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'browser:home' %}">Open Product Data</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'browser:download' %}">Download Data</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">OKFN</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">...</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!-- Begin page content -->


{% block content %}{% endblock %}


		    <footer class="footer">
		      <div class="container">
						<p class="text-muted">
							<a href="http://okfn.org/terms-of-use/">Terms of use</a> -
							<a href="http://okfn.org/privacy-policy/">Privacy policy</a> -
							<a href="http://okfn.org/ip-policy/">IP Policy</a>
					 </p>
		      </div>
		    </footer>


		    <!-- Bootstrap core JavaScript
		    ================================================== -->
		    <!-- Placed at the end of the document so the pages load faster -->
		    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		    <script>window.jQuery || document.write('<script src="{% static 'browser/js/jquery.min.js' %}"><\/script>')</script>
		    <script src="{% static 'browser/js/bootstrap.min.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js"></script>
		    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
		    <script src="{% static 'browser/js/menu.cssie10-viewport-bug-workaround.js' %}"></script>
		  </body>
		</html>

browser/templates/browser/brand_owner.html
{% extends "browser/base.html" %}
{% load static %}
{% block content %}



<div class="container">
  <div class="page-header">
    <h1>{{owner_detail.OWNER_NM}} - Brand list</h1>
  </div>
</div>

<div class="list-header">
  <div class="container">

            <table border="0" cellspacing="0px" cellpadding="0px">
            <tr>
                <td>
                  <!-- {{MEDIA_URL}}owner/{{owner_detail.OWNER_CD|stringformat:"06d"}}.jpg -->
                  <img class="thumbnail-list"
                    src="{% url 'browser:show_owner_img' owner_detail.OWNER_CD|stringformat:"06d" %}"
                    title="{{owner_detail.OWNER_NM}}" alt="{{owner_detail.OWNER_NM}}"
                    onerror="this.src='{% static 'browser/img/coming-soon.jpg' %}';"  >
                </td>
                <td>
					<b>Owner name</b> : {{owner_detail.OWNER_NM}}<br><br>
                    <b>Website</b> : <a href="{{owner_detail.OWNER_LINK}}" target="_blank" rel="nofollow">{{owner_detail.OWNER_LINK}}</a><br>
                    <br>
                    <img src="{% static 'browser/img/35px-Wikipedia-logo.png' %}" > <a href="{{owner_detail.OWNER_WIKI_EN}}" target="_blank" rel="nofollow">See the article on Wikipedia</a><br>
                </td>
            </tr>
            </table>
  </div>
</div>
	{% if brand_list %}

		{% for Brand in brand_list %}
    <div class="list-item">
  		<div class="container">
  	    <table>
        <tr>
            <td>
                	<a href="brand-{{Brand.BSIN}}" >
                    <!-- {{MEDIA_URL}}brand/{{Brand.BSIN}}.jpg -->
                    <img class="thumbnail-list"
                        src="{% url 'browser:show_brand_img' Brand.pk %}"
                        alt="{{Brand.BRAND_NM}}"
                        title="{{Brand.BRAND_NM}}"
                        onerror="this.src='{% static 'browser/img/coming-soon.jpg' %}';"  >
                    </a>
              </td>
              <td>
                <h2>{{Brand.BRAND_NM}}</h2>

               <b>BSIN</b> :  {{Brand.BSIN}} <br >
                {% if Brand.BRAND_NM %} <b>Brand name</b> : {{Brand.BRAND_NM}} <br>{% endif %}
                <br><br>
                >> <a href="brand-{{Brand.BSIN}}" > Voir la liste des produits </a>

              </td>
          </tr>
        </table>
        <hr>
      </div>
    </div>
		{% endfor %}
	{% endif %}
</div>
 {% endblock %}

browser/templates/browser/brand_owner_list.html
{% extends "browser/base.html" %}
{% load static %}
{% block content %}

<div class="container">
	<div class="page-header">
		<h1>Browse by Owners</h1>
	</div>

{% if owner_list %}
<section class="row">
	{% for Owner in owner_list %}
	<div class="col-xs-4 col-sm-3 col-md-2">
			<a href="owner-{{Owner.OWNER_CD|stringformat:"06d"}}">
					<!-- {{MEDIA_URL}}owner/{{Owner.OWNER_CD|stringformat:"06d"}}.jpg -->
				  <img class="thumbnail-list"
					src="{% url 'browser:show_owner_img' Owner.OWNER_CD|stringformat:"06d" %}"
					title="Owner - {{Owner.OWNER_NM}}"
					alt="Owner - {{Owner.OWNER_NM}}"
					onerror="this.src='{% static 'browser/img/coming-soon.jpg' %}';" >
			</a>
			<p>{{Owner.OWNER_NM}}</p>
  </div>
	{% endfor %}
</section>
{% endif %}
</div>
</div>
{% endblock %}

browser/templates/browser/home.html
{% extends "browser/base.html" %}
{% load static %}
{% block content %}



<div class="container">
		<div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading">Let's browse Open Product Data </h2>
          <p class="lead">Use the GTIN-13 code printed just below the barcode of any kind of product. If the code is composed of only 12 digits, add a zero in front of the code to get a valide GTIN-13 code.</p>

					<form class="form-search" action="{% url 'browser:search' %}" method="post">
						{% csrf_token %}
		        <label for="inputEmail" class="sr-only">GTIN search</label>
		        <input name="gtin" type="text" class="form-control" placeholder="Search a GTIN-13 Code" required="" autofocus="">
		        <button class="btn btn-lg btn-primary" type="submit">></button>
		      </form>
					{% if error_message %}<p>{{ error_message }}</p>{% endif %}

        </div>
        <div class="col-md-5 col-md-pull-7">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/400x400/auto" alt="Open Product Data" src="{% static 'browser/img/opd_logo_400.png' %}" data-holder-rendered="true">
        </div>
    </div>
</div>

<div class="home-browse">
	<div class="container">
			<div class="row">
			        <div class="col-lg-4">
			          <a href="brand-list-a"><img class="img-circle" src="{% static 'browser/img/navigate-brand.jpg' %}" alt="Generic placeholder image" width="140" height="140"></a>
			          <h2>Browse by Brand</h2>
			          <p></p>
			        </div><!-- /.col-lg-4 -->
			        <div class="col-lg-4">
			          <a href="{% url 'browser:owner_list' %}"><img class="img-circle" src="{% static 'browser/img/navigate-owner.jpg' %}" alt="Generic placeholder image" width="140" height="140"></a>
			          <h2>Browse by Owner</h2>
								<p></p>
			        </div><!-- /.col-lg-4 -->
			        <div class="col-lg-4">
			          <a href="{% url 'browser:nutrition' %}"><img class="img-circle" src="{% static 'browser/img/nutrition2.jpg' %}" alt="Generic placeholder image" width="140" height="140"></a>
			          <h2>Nutrition Facts</h2>
			          <p></p>
							</div>
			  </div><!-- /.col-lg-4 -->
			</div>
	</div>

<div class="home-participate">
	<div class="container">
			<h2 >You want to participate ? Let's join on <a href="https://github.com/okfn/opd-product-browser-web"> Github </a> !</h2> 
			<img src="{% static 'browser/img/python-django.jpg' %}">
	</div>
</div>



{% endblock %}